### ISSUE TITLE
broken set_option_exit_strategy

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#32] opened 2024-08-05 16:32 UTC
It doesn't work with short ticker.
This 5 options is already existing in portfolio.

![зображення](https://github.com/user-attachments/assets/926f8341-82b5-4f0c-829d-1fa4145c3461)

**Comment by b0noI** [comment] 2024-08-08 03:49
somhow I was not able to reproduce, can you try again and see maybe it is working now. please reopone if it still does not wrok

**Comment by seralekseenko** [comment] 2024-08-09 14:15
It is still broken.

![зображення](https://github.com/user-attachments/assets/88ae9755-3015-43e3-a86b-6745dd2501f6)

**Comment by seralekseenko** [comment] 2024-08-09 14:23
```json
{"content": "can not sell, since no suitable owned option contract found."}
```

**Comment by b0noI** [comment] 2024-08-11 01:36
closing since function now deleted

**Closed by b0noI** 2024-08-11 01:36 UTC
Labels: bug
